# gdal-warp-binding
# NOTE: base.libs 顺序为依赖图拓扑序(被依赖者在前),由脚本生成并校验,勿手动调整
gdal.warp.binding.version=v3.6.4

# amd64 | x86_64 :
amd64.base.libs=libcom_err.so.2,libgeos.so.3.10.2,libgeos_c.so.1,libidn.so.11,libjbig.so.2.0,libjpeg.so.62,libkeyutils.so.1,liblber-2.4.so.2,libnspr4.so,libpcre.so.1,libplc4.so,libplds4.so,libnssutil3.so,libnss3.so,libselinux.so.1,libkrb5support.so.0,libk5crypto.so.3,libkrb5.so.3,libgssapi_krb5.so.2,libsasl2.so.3,libsmime3.so,libssl3.so,libz.so.1,libcrypto.so.10,libsqlite3.so.0,libssl.so.10,libldap-2.4.so.2,libssh2.so.1,libcurl.so.4,libtiff.so.5,libproj.so.25,libgdal.so.32,libgdalalljni.so
amd64.proj.db=proj.db
amd64.gdal.lib=libgdal.so.32,libgdalalljni.so

# arm64 | aarch64 :
arm64.base.libs=libcom_err.so.2,libgeos.so.3.10.2,libgeos_c.so.1,libidn.so.11,libjbig.so.2.0,libjpeg.so.62,libkeyutils.so.1,liblber-2.4.so.2,libnspr4.so,libpcre.so.1,libplc4.so,libplds4.so,libnssutil3.so,libnss3.so,libselinux.so.1,libkrb5support.so.0,libk5crypto.so.3,libkrb5.so.3,libgssapi_krb5.so.2,libsasl2.so.3,libsmime3.so,libsqlite3.so.0,libssl3.so,libz.so.1,libcrypto.so.10,libssl.so.10,libldap-2.4.so.2,libssh2.so.1,libcurl.so.4,libtiff.so.5,libproj.so.25,libgdal.so.32,libgdalalljni.so
arm64.proj.db=proj.db
arm64.gdal.lib=libgdal.so.32,libgdalalljni.so

# windows:
win.base.libs=brotlicommon.dll,brotlidec.dll,brotlienc.dll,geos.dll,geos_c.dll,iconv-2.dll,freexl.dll,libcrypto-1_1-x64.dll,libexpat.dll,liblzma.dll,libssl-1_1-x64.dll,libmysql.dll,libpq.dll,msvcr100.dll,openjp2.dll,pcre.dll,pthreadVC2.dll,sqlite3.dll,xerces-c_3_2.dll,zlib.dll,libcurl.dll,libpng16.dll,libxml2.dll,ogdi.dll,tiff.dll,proj_9_1.dll,proj_9_2.dll,spatialite.dll,zstd.dll
win.proj.db=proj.db
win.gdal.lib=gdal.dll,gdalalljni.dll
