# gdal-warp-binding
gdal.warp.binding.version=v3.6.4

# amd64 | x86_64 :
amd64.base.libs=libsqlite3.so.0,libjbig.so.2.0,libjpeg.so.62,libtiff.so.5,libgeos.so.3.10.2,libgeos_c.so.1,libproj.so.25
amd64.proj.db=proj.db
amd64.gdal.lib=libgdal.so.32,libgdalalljni.so

# arm64 | aarch64 :
arm64.base.libs=libsqlite3.so.0,libjbig.so.2.0,libjpeg.so.62,libtiff.so.5,libgeos.so.3.10.2,libgeos_c.so.1,libproj.so.25
arm64.proj.db=proj.db
arm64.gdal.lib=libgdal.so.32,libgdalalljni.so

# windows:
win.base.libs=tiff.dll,geos_c.dll,proj_9_1.dll
win.proj.db=proj.db
win.gdal.lib=gdal.dll,gdalalljni.dll
